# server information
[server]
brokerId = "broker"
port = 5559
granularity = 5
messageProcessors = 1
# logConfFile = "./test-log.xml" # specify another config file to be used
# prometheusPort = 1234 # use prometheus with given port; providing no port disables prometheus.

    # server mode specific information (only one should be uncommented)
    [server.mode]
    name = "single"

#   [server.mode]
#   name = "single_noGeo"



